### ISSUE TITLE
Array.y() cuts off if an item is longer than the previous

### ISSUE THREAD

**Issue by ETHproductions** [ETHproductions/Japt#12]
The array transpose function `y` swaps the array's rows with it's columns. For example, the program

    Ny qR

with an input of

    [0 1 2]
    [3 4 5]
    [6 7 8]

outputs

    0,3,6
    1,4,7
    2,5,8

However, this does not work if one of the items is longer than the one before it. As an example, the above program run with input 

    [0    ]
    [3 4  ]
    [6 7 8]

outputs

    0,3,6

when the correct output would be

    0,3,6
    ,4,7
    ,,8

[Test it here](http://ethproductions.github.io/japt?v=master&code=TnkgcVI=&input=WzAgICAgXQpbMyA0ICBdCls2IDcgOF0=)

The current setup for this function is based on `.map`. I think it would be better to create a double `for`-loop that loops through each `x` and `y` in the 2D array, putting the item at (x:`y`, y:`x`) in the new array. If the array is full of strings, this will also require filling each item in the new array with a space, then joining them after the loop.

**Comment by vihanb** [comment]
The easiest fix I think would be to just balance the row lengths and implement another built-in to balance a 2D array.

**Comment by ETHproductions** [comment]
Fixed in the latest commit.

I would use `" "` in the blanks in strings, as that is what is usually needed in a code-golf-practical sense. I'd also just use `undefined` in the arrays.

**Comment by ETHproductions** [comment]
Fixed in commit 742ef15.

I would use `" "` to fill in the empty items for strings, as that's probably the most practical option for code-golf. I'd also just use `undefined` in arrays.
