### ISSUE TITLE
Compression strings do not work with quotes inside of them

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [ETHproductions/Japt#18]
One might think that within a compression string, `"` quotes would work, but they do not. Is this a bug, or by design? Example: (code, expected output, what one gets)

    `He Ñ· "HÁM!"`
    "He said, \"Hello!\""
    "He said, "Hello!"" (syntax error).

[Online.](http://ethproductions.github.io/japt?v=master&code=YEhlING3ICJIwU0hImA=&input=ImFiYyIgMTMgWzkgInp5eCJd)

**Comment by ETHproductions** [comment]
I know about this, and it will be fixed in the update I'll push in a few minutes (most of which was written before you posted this issue ;) ). But thanks for posting this here.

**Comment by ConorOBrien-Foxx** [comment]
My pleasure! Good to know you're an avid bug fixer ;)
