### ISSUE TITLE
Proposal for Saving Bytes

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [ETHproductions/japt#20]
Looking at the source for Japt, it appears to be the case that Japt has a lot of unused single-bytes ISO-8859-1 tokens; if this is the case, then perhaps you can devote a few of them as transpiling with a fixed arity. I'm still not entirely sure how Japt performs transpilations (I'd have to read the source a few more times to fully understand it), so I'm not sure if you can have fixed arities. If you can, this will often shave a byte in an expression.

You still seem to have these characters open:

```
 Ñ Ò Ó Ô Õ Ö × Ø Ù Ú Û Ü Ý Þ ß à á â ã ä å æ ç è é ê ë ì í î ï ð ñ ò ó ô õ ö ÷ ø ù ú û ü ý þ ÿ
```

I propose that `þ` transpiles to `c(space)` and that `ß` transpiles to `s(value)(space)`. Again, I'm not sure if the latter is possible, but if it is, then it would save you bytes in many situations.

**Comment by ETHproductions** [comment]
Thanks for the input! The following characters are reserved for more functions:

    à á â ã ä å æ ç è é ê ë ì í î ï ð ñ ò ó ô õ ö ø ù ú û ü ý þ ÿ ß

Some of these are already in use. But the others can be used for Unicode Shortcuts, as vihanb calls them. I think `c(space)` would be a good one, and can be implemented without any modification to the source. But `s(value)(space)` would be more tricky; how do you know if `5ßUp3` is supposed to mean `5sU p3` or `5sUp3`? However, I think putting it after the value just might work. `5Ußp3` would be undoubtedly `5sU p3`. I'll think about it more.

**Comment by ConorOBrien-Foxx** [comment]
Cool! Thanks for looking it over.

**Comment by ETHproductions** [comment]
I've implemented `ß` as a recursion function (calls the entire program as a function), but perhaps I'll implement this with another letter in the near future.

**Comment by ETHproductions** [comment]
I'm closing this, as I don't believe the `ß` idea could be feasible anymore; see #19.
