### ISSUE TITLE
`Error: Japt.stdout must be sent to an HTMLElement`

### ISSUE THREAD

**Issue by schas002** [ETHproductions/japt#21]
I tried to run [@ETHproductions' program](https://github.com/schas002/nested-programs/pull/2) for my [nested programs](https://github.com/schas002/nested-programs) challenge (try it online: <http://ethproductions.github.io/japt/?v=master&code=YHDOQyLDAHQoJ1NUT1AhJyki&input=>), and I got this error:

```
Error: Japt.stdout must be sent to an HTMLElement
```

The code was all correct. Apparently it's a bug in the interpreter.

The Stack Exchange chatroom is frozen, and I don't think ETHproductions is active on SE, so I'm posting this bug as an issue there.

Browser used is latest Firefox (Mozilla/5.0 (Windows NT 6.0; rv:45.0) Gecko/20100101 Firefox/45.0). Also, apparently, this bug makes *all* programs fail (see: <http://ethproductions.github.io/japt?v=master&code=W1UsVipXZyAsV2cxXXFT&input=ImFiYyIgMTMgWzkgInp5eCJd>).

**Comment by ETHproductions** [comment]
I've known about this for a while, but I still don't know why it happens. Refreshing the page usually helps.

**Comment by schas002** [comment]
I tried a few times. It doesn't help.

**Comment by ETHproductions** [comment]
Should be fixed now. Can you please try again?

**Comment by schas002** [comment]
It works!
