### ISSUE TITLE
Does not work under nodejs

### ISSUE THREAD

**Issue by AndrewSav** [ETHproductions/japt#26]
[This commit](https://github.com/ETHproductions/japt/commit/4cc9dee8593e8c1cbc86ca727ce1289b70172f8b) broke nodejs. window object is not available under nodejs. "K" should be added only if `isnode` is falsy.

**Comment by AndrewSav** [comment]
PR: https://github.com/ETHproductions/japt/pull/27

**Comment by ETHproductions** [comment]
Fixed in 55e651c.
