### ISSUE TITLE
Random Question about Random Numbers

### ISSUE THREAD

**Issue by tkellehe** [ETHproductions/japt#32]
Hello,
I really like how condensed _Japt_ makes _JavaScript_. So, I was attempting to learn _Japt_ but got confused. The code `Mr1,4` from what I understand should give me a random number between `1` and `4`. Instead I get numbers bigger than `4`. Am I misunderstanding something? I tried to read through the source code but did not help me figure it out.

**Comment by ETHproductions** [comment]
Hey @tkellehe,

Thanks for bringing this up. Apparently both `Mr` and `Mq` don't generate a random number between the first number (n1) and the second (n2), but between n2 and n2+n1. I don't think this is how I intended it to be, so I'll fix it later today.

**Comment by ETHproductions** [comment]
Fixed in 43038e2.

**Comment by tkellehe** [comment]
Thanks! And you added some more stuff, cool!!
