### ISSUE TITLE
Add a shortcut for XYZ{X

### ISSUE THREAD

**Issue by PeterShaggyNoble** [ETHproductions/japt#34]
[This](https://codegolf.stackexchange.com/a/122452/58974) got me to thinking that it might be handy to have a shortcut for `XYZ{X`, similar to `@` for `XYZ{` and `_` for `Z{Z` (`™` maybe?), with a corresponding shortcut for `m™`.

**Comment by ETHproductions** [comment]
Hmm, perhaps. I have seen `@X` used quite often (when you need the index or original array). I'll add this to the list of ideas to implement :-)

**Comment by PeterShaggyNoble** [comment]
Thanks for adding this, @ETHproductions.

**Comment by ETHproductions** [comment]
Oh sorry, fixed in 6c153b2.
