### ISSUE TITLE
Array.o() infinite loop

### ISSUE THREAD

**Issue by jmariner** [ETHproductions/japt#37]
The `Array.o()` function runs in an infinite loop if the argument given to it is both
* `> 1`
* *not* an integer

For example, [`[1,2,3]o1.5`][2]. This seems to be due to the fact that the loop used in [that function][1] relies on the counter becoming equal to zero, and that never occurs with a non-integer value.

[1]:https://github.com/ETHproductions/japt/blob/master/src/japt-interpreter.js#L194
[2]:http://ethproductions.github.io/japt/?v=1.4.5&code=WzEsMiwzXW8xLjU=&input=

**Comment by ETHproductions** [comment]
*slaps 2015 me across the face*

But seriously, I'll get this taken care of when I have a chance, probably tomorrow but maybe later. (BTW, how did you run across this?)

**Comment by jmariner** [comment]
Found it when working on [Fold a List in Half][1] on PPCG; I was trying to pop the last `Ul /2` items from the array and that would crash on an odd input array length. (I did get it working using `Number.c()` though)

[1]: https://codegolf.stackexchange.com/q/136887/69583

**Comment by ETHproductions** [comment]
So for some reason it only occured to me *now*, 2 days later, that you're talking about Number.o() instead of Array.o(). I think the entire conversation makes sense either way though, other than the bug not existing on Number.o()...

Should be fixed now.
