### ISSUE TITLE
Add f? to A.v

### ISSUE THREAD

**Issue by Etheryte** [ETHproductions/japt#44]
Currently, `A.v` simply returns the first element. Optionally feeding the result through `f?` would make it behave more like other methods and save some bytes too.

For example, with `.m`, you can do

    [1,2,3]m+1

Currently, with `.v`, you have to do

    [1,2,3]v +1

Adding an optional function would allow us to save one byte:

    [1,2,3]v+1

The same argument could be made for a number of methods that don't currently take arguments.

**Comment by Etheryte** [comment]
This would be obsolete once https://github.com/ETHproductions/japt/issues/19 gets implemented.

**Comment by ETHproductions** [comment]
You know what, this may actually be a great idea for both `A.v()` and `A.o()`, separate from #19. Currently to edit the last item in an array you have to do e.g. `UpUo p4`, but simply `Uop4` could work too and would be much shorter. If you don't mind, I'll reopen this issue for now.

**Comment by ETHproductions** [comment]
I should also mention that Japt v2 will have a lot of fixed-arity methods, including arity-0 methods for the current `A.o()` and `A.v()`. This is more toward your original intention I believe...
