### ISSUE TITLE
A.c() adds unnecessary elements to the returned array

### ISSUE THREAD

**Issue by Bubbler-4** [ETHproductions/japt#48]
Example program:

```
[['H]['H]]c
```

Expected output (with `-Q`):

```
["H","H"]
```

Actual output (with `-Q`):

```
["H",null,null,"H",null,null]
```

Using `-R` instead shows two functions, namely `Array.prototype.contains` and `Array.prototype.sortBy`.

Reproducible on [v2.0a0](https://ethproductions.github.io/japt/?v=2.0a0&code=W1snSF1bJ0hdXWM=&input=LVE=). The function works as expected on [v1.4.5](https://ethproductions.github.io/japt/?v=1.4.5&code=W1snSF1bJ0hdXWM=&input=LVE=).

Possible cause:

https://github.com/ETHproductions/japt/blob/90d14016a5a4675c8c20243cb63ccbcea830c0b6/src/japt.js#L775-L779

Possible solution: `f.push(...q);` or check if the index is a number.

**Comment by ETHproductions** [comment]
Fixed in 4887b61.
