### ISSUE TITLE
Parens balancing algorithm needs several improvements

### ISSUE THREAD

**Issue by Bubbler-4** [ETHproductions/japt#51]
Found while solving [this PPCG challenge](https://codegolf.stackexchange.com/q/101231/78410).

Real example: ([link](https://ethproductions.github.io/japt/?v=2.0a0&code=W11Ms/VAcFhrIGNY7Cn4NyA/VWdWKys6WApzN3A3IC1BLDdwNw==&input=))

```
[]L³õ@pXk cXì)ø7 ?UgV++ :X
s7p7 -A,7p7
```

Transpiled code:

```
U = [], L.p(3).õ(function(X, Y, Z) { return U.p(X.k().c(X.ì()).ø(7) ? U.g((V++))) : X }); U.s(7 .p(7) - A, 7 .p(7))
```

Since the parens are not balanced inside `?:` operator, SyntaxError is raised.

Erasing the space results in erasing **two** closing parens at the end of `V++`, so the SyntaxError persists.

---

There is another problem regarding `?:` ternary operator: the balancing algorithm treats it as any other binary or unary operator. As a simple example, Japt code `xA?(B:C` transpiles into `U.x(A ? (B : C))` which is clearly a syntax error. The algorithm should consider the `?...:` region as an isolated context, so the parens are always balanced inside the region.

**Comment by ETHproductions** [comment]
Fixed in e837e44; parentheses are now balanced within `?:`, similarly to how they are within `{}`. Adding default values to allow an empty slot in the ternary may be in the near future.
