### ISSUE TITLE
Overloading Base Conversion Methods

### ISSUE THREAD

**Issue by PeterShaggyNoble** [ETHproductions/japt#53]
The following additions to `S.n()` , `A.ì()`, `N.s()` & `N.ì()` would be handy to have:

- **`S.n(x,x)` /  `A.ì(x,x)`**: convert from base `x1` to base `x2`.
- **`S.n(x,f)` /  `A.ì(x,f)`**: convert from base `x`, apply `f` and convert back to base `x`.
- **`S.n(x,x,f)` /  `A.ì(x,x,f)`**: convert from base `x1`, apply `f` and convert to base `x2`.
- **`N.s(x,f) / N.ì(x,f)`**: convert to base `x`, apply `f` and convert back to integer.

**Comment by ETHproductions** [comment]
Good ideas, I'll see if I can implement them today.
