### ISSUE TITLE
Line Breaks in Transpiled Code

### ISSUE THREAD

**Issue by PeterShaggyNoble** [ETHproductions/japt#54]
The transpiled code is a great tool for helping debug a programme but, for some reason, I often struggle to find the section I want when writing multi-line programmes.

Would it be possible to have the transpiled code preserve the line breaks in a programme? I'm *assuming* the fact that it doesn't is a holdover from the days before Japt could handle multiple lines and that it's  a simple "fix"?

**Comment by ETHproductions** [comment]
Yeah, should be a quick change, I'll see what I can do.

**Comment by PeterShaggyNoble** [comment]
Thanks. That's going to be a big help.
